AM_CPPFLAGS = -Wall
AM_CFLAGS 	=
AM_CXXFLAGS =
AM_LDFLAGS 	=

AM_CPPFLAGS += -DBOOST_ALLOW_DEPRECATED_HEADERS=1
AM_CPPFLAGS += $(BOOST_CPPFLAGS)
AM_LDFLAGS  += $(BOOST_LDFLAGS)
AM_LDFLAGS  += $(BOOST_SYSTEM_LIB)
AM_LDFLAGS  += $(BOOST_THREAD_LIB)
AM_LDFLAGS  += $(BOOST_CHRONO_LIB)
AM_LDFLAGS  += $(BOOST_ASIO_LIB)

AM_CPPFLAGS += $(GTEST_CPPFLAGS)
AM_CXXFLAGS += $(GTEST_CXXFLAGS)
AM_LDFLAGS  += $(GTEST_LDFLAGS)
AM_LDFLAGS  += $(GTEST_LIBS) -lgtest_main

check_PROGRAMS =

check_PROGRAMS += test-hello
test_hello_SOURCES = test-hello.cc

TESTS = $(check_PROGRAMS)
